sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t avattam/docker-react-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true avattam/docker-react-frontend npm run test
